// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6tVFedu9c7F0_BADsWydNRKpI2iTlBzk',
    appId: '1:683642339193:web:093aed4f690c695b83f9a8',
    messagingSenderId: '683642339193',
    projectId: 'chatapp-friendly',
    authDomain: 'chatapp-friendly.firebaseapp.com',
    databaseURL: 'https://chatapp-friendly-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-friendly.appspot.com',
    measurementId: 'G-BLD0DE1CZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI6Lb7xEe2feIq2YYjm2xNcfjP3QAUQdM',
    appId: '1:683642339193:android:9146cbda39daca0f83f9a8',
    messagingSenderId: '683642339193',
    projectId: 'chatapp-friendly',
    databaseURL: 'https://chatapp-friendly-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-friendly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuRDuGNzy4DrCVTzzUdpjitbI1fbJ7Wbc',
    appId: '1:683642339193:ios:488742e550aaf0a783f9a8',
    messagingSenderId: '683642339193',
    projectId: 'chatapp-friendly',
    databaseURL: 'https://chatapp-friendly-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-friendly.appspot.com',
    iosClientId: '683642339193-lat09eec0ggo2q6bdtj327l8rhu1fuj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.voterapp',
  );
}
