class ConstituencyList {
  static List<String> items = [
    "Agra Cantonment",
    "Agra North",
    "Agra Rural",
    "Agra South",
    "Ajagara",
    "Akbarpur",
    "Akbarpur-Raniya",
    "Alapur",
    "Aliganj",
    "Aligarh",
    "Allahabad North",
    "Allahabad South",
    "Allahabad West",
    "Amanpur",
    "Amethi",
    "Amritpur",
    "Amroha",
    "Anupshahr",
    "Aonla",
    "Arya Nagar",
    "Asmoli",
    "Atrauli",
    "Atrauliya",
    "Aurai",
    "Auraiya",
    "Ayah Shah",
    "Ayodhya",
    "Azamgarh",
    "Babaganj",
    "Baberu",
    "Babina",
    "Bachhrawan",
    "Badaun",
    "Badlapur",
    "Baghpat",
    "Bah",
    "Baheri",
    "Bahraich",
    "Bairia",
    "Bakshi Kaa Talab",
    "Balamau",
    "Baldev",
    "Balha",
    "Ballia Nagar",
    "Balrampur",
    "Banda",
    "Bangermau",
    "Bansdih",
    "Bansgaon"
        "Bansgaon",
    "Bansi",
    "Bara",
    "Barabanki",
    "Barauli",
    "Baraut",
    "Bareilly Cantonment",
    "Bareilly",
    "Barhaj",
    "Barhapur",
    "Barkhera",
    "Basti Sadar",
    "Behat",
    "Belthara Road",
    "Bhadohi",
    "Bhagwantnagar",
    "Bharthana",
    "Bhatpar Rani",
    "Bhinga",
    "Bhognipur",
    "Bhojipura",
    "Bhojpur",
    "Bhongaon",
    "Bidhuna",
    "Bijnor",
    "Bikapur",
    "Bilari",
    "Bilaspur",
    "Bilgram-Mallanwan",
    "Bilhaur",
    "Bilsi",
    "Bindki",
    "Bisalpur",
    "Bisauli",
    "Biswan",
    "Bithari Chainpur",
    "Bithoor",
    "Budhana",
    "Bulandshahr",
    "Caimpiyarganj",
    "Chail",
    "Chakia",
    "Chamraua",
    "Chandausi",
    "Chandpur",
    "Charkhari",
    "Charthawal",
    "Chauri-Chaura",
    "Chhanbey",
    "Chhaprauli",
    "Chharra",
    "Chhata",
    "Chhibramau",
    "Chillupar",
    "Chitrakoot",
    "Chunar",
    "Colonelganj",
    "Dadraul",
    "Dadri",
    "Dariyabad",
    "Dataganj",
    "Debai",
    "Deoband",
    "Deoria",
    "Dhampur",
    "Dhanaura",
    "Dhanghata",
    "Dhaulana",
    "Dhaurahra"
        "Dhaurahra",
    "Dibiyapur",
    "Didarganj",
    "Domariyaganj",
    "Duddhi",
    "Erich",
    "Etah",
    "Etawah",
    "Etmadpur",
    "Faridpur",
    "Farrukhabad",
    "Fatehabad",
    "Fatehpur Sikri",
    "Fatehpur",
    "Fazilnagar",
    "Firozabad",
    "Gainsari",
    "Gangoh",
    "Garautha",
    "Garhmukteshwar",
    "Gaura",
    "Gauriganj",
    "Ghatampur",
    "Ghaziabad",
    "Ghazipur",
    "Ghorawal",
    "Ghosi",
    "Gola Gokrannath",
    "Gonda",
    "Gopalpur",
    "Gopamau",
    "Gorakhpur Rural",
    "Gorakhpur Urban",
    "Goshainganj",
    "Goverdhan",
    "Govind Nagar",
    "Gunnaur",
    "Gyanpur",
    "Haidergarh",
    "Hamirpur",
    "Handia",
    "Hapur",
    "Harchandpur",
    "Hardoi",
    "Hargaon",
    "Harraiya",
    "Hasanpur",
    "Hastinapur",
    "Hata",
    "Hathras",
    "Husainganj",
    "Iglas",
    "Isauli",
    "Itwa",
    "Jagdishpur",
    "Jahanabad",
    "Jakhania",
    "Jalalabad",
    "Jalalpur",
    "Jalesar",
    "Jangipur",
    "Jasrana",
    "Jaswantnagar",
    "Jaunpur",
    "Jewar",
    "Jhansi Nagar",
    "Kadipur",
    "Kaimganj",
    "Kairana",
    "Kaiserganj",
    "Kalpi",
    "Kalyanpur",
    "Kannauj",
    "Kanpur Cantonment",
    "Kanth",
    "Kapilvastu",
    "Kaptanganj",
    "Karachhana",
    "Karhal",
    "Kasganj",
    "Kasta",
    "Katehari",
    "Katra Bazar",
    "Katra",
    "Kerakat",
    "Khadda",
    "Khaga",
    "Khair",
    "Khajani",
    "Khalilabad",
    "Khatauli",
    "Kheragarh",
    "Khurja",
    "Kidwai Nagar",
    "Kishni",
    "Kithore",
    "Koil",
    "Koraon",
    "Kunda",
    "Kundarki",
    "Kursi",
    "Kushinagar",
    "Laharpur",
    "Lakhimpur",
    "Lalganj",
    "Lalitpur",
    "Lambhua",
    "Loni",
    "Lucknow Cantonment",
    "Lucknow Central",
    "Lucknow East",
    "Lucknow North",
    "Lucknow West",
    "Machhlishahr",
    "Madhaugarh",
    "Madhuban",
    "Mahadewa",
    "Maharajganj",
    "Maharajpur",
    "Mahasi",
    "Mahmoodabad",
    "Mahoba",
    "Maholi",
    "Mainpuri",
    "Majhawan",
    "Malhani",
    "Malihabad",
    "Manikpur",
    "Manjhanpur",
    "Mankapur",
    "Mant",
    "Marhara",
    "Marihan",
    "Mariyahu",
    "Matera",
    "Mathura",
    "Mau",
    "Mauranipur",
    "Meerapur",
    "Meerganj",
    "Meerut Cantonment",
    "Meerut South",
    "Meerut",
    "Mehnagar",
    "Mehnaun",
    "Mehroni",
    "Meja",
    "Menhdawal",
    "Milak",
    "Milkipur",
    "Mirzapur",
    "Misrikh",
    "Modi Nagar",
    "Mohammadabad",
    "Mohammdi",
    "Mohan",
    "Mohanlalganj",
    "Moradabad Nagar",
    "Moradabad Rural",
    "Mubarakpur",
    "Mughalsarai",
    "Muhammadabad-Gohna",
    "Mungra Badshahpur",
    "Muradnagar",
    "Muzaffar Nagar",
    "Nagina",
    "Najibabad",
    "Nakur",
    "Nanpara",
    "Naraini",
    "Naugawan Sadat",
    "Nautanwa",
    "Nawabganj",
    "Nehtaur",
    "Nighasan",
    "Nizamabad",
    "Noida",
    "Noorpur",
    "Obra",
    "Orai",
    "Padrauna",
    "Palia",
    "Paniyara",
    "Pathardeva",
    "Patiyali",
    "Patti",
    "Payagpur",
    "Phaphamau",
    "Pharenda",
    "Phephana",
    "Phoolpur-Pawai",
    "Phulpur",
    "Pilibhit",
    "Pindra",
    "Pipraich",
    "Powayan",
    "Pratapgarh",
    "Pratappur",
    "Puranpur",
    "Purqazi",
    "Purwa",
    "Rae Bareli",
    "Ram Nagar",
    "Ramkola",
    "Rampur Karkhana",
    "Rampur Khas",
    "Rampur Maniharan",
    "Rampur",
    "Raniganj",
    "Rasara",
    "Rasulabad",
    "Rath",
    "Robertsganj",
    "Rohaniya",
    "Rudauli",
    "Rudhauli",
    "Rudrapur",
    "Sadabad",
    "Sadar",
    "Safipur",
    "Sagri",
    "Sahajanwa",
    "Saharanpur Nagar",
    "Saharanpur",
    "Sahaswan",
    "Sahibabad",
    "Saidpur",
    "Saiyadraja",
    "Sakaldiha",
    "Salempur",
    "Salon",
    "Sambhal",
    "Sandi",
    "Sandila",
    "Sardhana",
    "Sareni",
    "Sarojini Nagar",
    "Sawayazpur",
    "Sevapuri"
        "Sevata",
    "Shahabad",
    "Shahganj",
    "Shahjahanpur",
    "Shamli",
    "Shekhupur",
    "Shikarpur",
    "Shikohabad",
    "Shivpur",
    "Shohratgarh",
    "Shrawasti",
    "Sidhauli",
    "Sikanderpur",
    "Sikandra Rao",
    "Sikandra",
    "Sikandrabad",
    "Sirathu",
    "Sirpur",
    "Sirsaganj",
    "Sishamau",
    "Siswa",
    "Sitapur",
    "Siwalkhas",
    "Soraon",
    "Sri Nagar",
    "Suar",
    "Sultanpur",
    "Syana",
    "Tamkuhi Raj",
    "Tanda",
    "Tarabganj",
    "Thakurdwara",
    "Thana Bhawan",
    "Tilhar",
    "Tiloi",
    "Tindwari",
    "Tirwa",
    "Tulsipur",
    "Tundla",
    "Unchahar",
    "Unnao",
    "Utraula",
    "Varanasi Cantonment",
    "Varanasi North",
    "Varanasi South",
    "Vishwanath Ganj",
    "Zafrabad",
    "Zahoorabad",
    "Zaidpur",
    "Zamania",
  ];
}
