class ConstituencyList {
  static List<String> items = [
    "Sirpur",
    "Etmadpur",
    "Agra Cantonment",
    "Agra South",
    "Agra North",
    "Jalesar",
    "Khair",
    "Barauli",
    "Atrauli",
    "Koil",
    "Aligarh",
    "Meja",
    "Karachhana",
    "Allahabad South",
    "Bara",
    "Koraon",
    "Goshainganj",
    "Katehari",
    "Tanda",
    "Jalalpur",
    "Akbarpur",
    "Tiloi",
    "Salon",
    "Jagdishpur",
    "Gauriganj",
    "Amethi",
    "Dhanaura",
    "Naugawan Sadat",
    "Amroha",
    "Hasanpur",
    "Garhmukteshwar",
    "Shekhupur",
    "Dataganj",
    "Faridpur",
    "Bithari Chainpur",
    "Aonla",
    "Gopalpur",
    "Sagri",
    "Mubarakpur",
    "Azamgarh",
    "Mehnagar",
    "Gunnaur",
    "Bisauli",
    "Sahaswan",
    "Bilsi",
    "Badaun",
    "Siwalkhas",
    "Chhaprauli",
    "Baraut",
    "Baghpat",
    "Modi Nagar",
    "Balha",
    "Nanpara",
    "Matera",
    "Mahasi",
    "Bahraich",
    "Phephana",
    "Ballia Nagar",
    "Bairia",
    "Zahoorabad",
    "Mohammadabad",
    "Baberu",
    "Naraini",
    "Banda",
    "Chitrakoot",
    "Manikpur",
    "Bansgaon"
        "Chauri-Chaura",
    "Bansgaon",
    "Chillupar",
    "Rudrapur",
    "Barhaj",
    "Kursi",
    "Ram Nagar",
    "Barabanki",
    "Zaidpur",
    "Haidergarh",
    "Meerganj",
    "Bhojipura",
    "Nawabganj",
    "Bareilly",
    "Bareilly Cantonment",
    "Harraiya",
    "Kaptanganj",
    "Rudhauli",
    "Basti Sadar",
    "Mahadewa",
    "Pratappur",
    "Handia",
    "Bhadohi",
    "Gyanpur",
    "Aurai",
    "Purqazi",
    "Meerapur",
    "Bijnor",
    "Chandpur",
    "Hastinapur",
    "Bulandshahr",
    "Syana",
    "Anupshahr",
    "Debai",
    "Shikarpur",
    "Mughalsarai",
    "Sakaldiha",
    "Saiyadraja",
    "Ajagara",
    "Shivpur",
    "Tamkuhi Raj",
    "Fazilnagar",
    "Deoria",
    "Pathardeva",
    "Rampur Karkhana",
    "Dhaurahra"
        "Dhaurahra",
    "Kasta",
    "Mohammdi",
    "Maholi",
    "Hargaon",
    "Shohratgarh",
    "Kapilvastu",
    "Bansi",
    "Itwa",
    "Domariyaganj",
    "Kasganj",
    "Amanpur",
    "Patiyali",
    "Etah",
    "Marhara",
    "Etawah",
    "Bharthana",
    "Dibiyapur",
    "Auraiya",
    "Sikandra",
    "Dariyabad",
    "Rudauli",
    "Milkipur",
    "Bikapur",
    "Ayodhya",
    "Aliganj",
    "Kaimganj",
    "Amritpur",
    "Farrukhabad",
    "Bhojpur",
    "Jahanabad",
    "Bindki",
    "Fatehpur",
    "Ayah Shah",
    "Husainganj",
    "Khaga",
    "Agra Rural",
    "Fatehpur Sikri",
    "Kheragarh",
    "Fatehabad",
    "Bah",
    "Tundla",
    "Jasrana",
    "Firozabad",
    "Shikohabad",
    "Sirsaganj",
    "Noida",
    "Dadri",
    "Jewar",
    "Sikandrabad",
    "Khurja",
    "Loni",
    "Muradnagar",
    "Sahibabad",
    "Ghaziabad",
    "Dhaulana",
    "Jakhania",
    "Saidpur",
    "Ghazipur",
    "Jangipur",
    "Zamania",
    "Madhuban",
    "Ghosi",
    "Muhammadabad-Gohna",
    "Mau",
    "Rasara",
    "Utraula",
    "Mehnaun",
    "Gonda",
    "Mankapur",
    "Gaura",
    "Caimpiyarganj",
    "Pipraich",
    "Gorakhpur Urban",
    "Gorakhpur Rural",
    "Sahajanwa",
    "Hamirpur",
    "Rath",
    "Mahoba",
    "Charkhari",
    "Tindwari",
    "Sawayazpur",
    "Shahabad",
    "Hardoi",
    "Gopamau",
    "Sandi",
    "Chharra",
    "Iglas",
    "Hathras",
    "Sadabad",
    "Sikandra Rao",
    "Bhognipur",
    "Madhaugarh",
    "Kalpi",
    "Orai",
    "Erich",
    "Garautha",
    "Badlapur",
    "Shahganj",
    "Jaunpur",
    "Malhani",
    "Mungra Badshahpur",
    "Babina",
    "Jhansi Nagar",
    "Mauranipur",
    "Lalitpur",
    "Mehroni",
    "Nakur",
    "Gangoh",
    "Kairana",
    "Thana Bhawan",
    "Shamli",
    "Payagpur",
    "Kaiserganj",
    "Katra Bazar",
    "Colonelganj",
    "Tarabganj",
    "Chhibramau",
    "Tirwa",
    "Kannauj",
    "Bidhuna",
    "Rasulabad",
    "Akbarpur-Raniya",
    "Bithoor",
    "Kalyanpur",
    "Maharajpur",
    "Ghatampur",
    "Govind Nagar",
    "Sishamau",
    "Arya Nagar",
    "Kidwai Nagar",
    "Kanpur Cantonment",
    "Babaganj",
    "Kunda",
    "Sirathu",
    "Manjhanpur",
    "Chail",
    "Palia",
    "Nighasan",
    "Gola Gokrannath",
    "Sri Nagar",
    "Lakhimpur",
    "Khadda",
    "Padrauna",
    "Kushinagar",
    "Hata",
    "Ramkola",
    "Atrauliya",
    "Nizamabad",
    "Phoolpur-Pawai",
    "Didarganj",
    "Lalganj",
    "Lucknow West",
    "Lucknow North",
    "Lucknow East",
    "Lucknow Central",
    "Lucknow Cantonment",
    "Machhlishahr",
    "Mariyahu",
    "Zafrabad",
    "Kerakat",
    "Pindra",
    "Pharenda",
    "Nautanwa",
    "Siswa",
    "Maharajganj",
    "Paniyara",
    "Mainpuri",
    "Bhongaon",
    "Kishni",
    "Karhal",
    "Jaswantnagar",
    "Chhata",
    "Mant",
    "Goverdhan",
    "Mathura",
    "Baldev",
    "Kithore",
    "Meerut Cantonment",
    "Meerut",
    "Meerut South",
    "Hapur",
    "Chhanbey",
    "Mirzapur",
    "Majhawan",
    "Chunar",
    "Marihan",
    "Misrikh",
    "Bilgram-Mallanwan",
    "Balamau",
    "Sandila",
    "Bilhaur",
    "Sidhauli",
    "Malihabad",
    "Bakshi Kaa Talab",
    "Sarojini Nagar",
    "Mohanlalganj",
    "Barhapur",
    "Kanth",
    "Thakurdwara",
    "Moradabad Rural",
    "Moradabad Nagar",
    "Budhana",
    "Charthawal",
    "Muzaffar Nagar",
    "Khatauli",
    "Sardhana",
    "Najibabad",
    "Nagina",
    "Dhampur",
    "Nehtaur",
    "Noorpur",
    "Phaphamau",
    "Soraon",
    "Phulpur",
    "Allahabad West",
    "Allahabad North",
    "Baheri",
    "Pilibhit",
    "Barkhera",
    "Puranpur",
    "Bisalpur",
    "Rampur Khas",
    "Vishwanath Ganj",
    "Pratapgarh",
    "Patti",
    "Raniganj",
    "Bachhrawan",
    "Harchandpur",
    "Rae Bareli",
    "Sareni",
    "Unchahar",
    "Suar",
    "Chamraua",
    "Bilaspur",
    "Rampur",
    "Milak",
    "Chakia",
    "Ghorawal",
    "Robertsganj",
    "Obra",
    "Duddhi",
    "Behat",
    "Saharanpur Nagar",
    "Saharanpur",
    "Deoband",
    "Rampur Maniharan",
    "Bhatpar Rani",
    "Salempur",
    "Belthara Road",
    "Sikanderpur",
    "Bansdih",
    "Kundarki",
    "Bilari",
    "Chandausi",
    "Asmoli",
    "Sambhal",
    "Alapur",
    "Menhdawal",
    "Khalilabad",
    "Dhanghata",
    "Khajani",
    "Katra",
    "Jalalabad",
    "Tilhar",
    "Powayan",
    "Shahjahanpur",
    "Dadraul",
    "Bhinga",
    "Shrawasti",
    "Tulsipur",
    "Gainsari",
    "Balrampur",
    "Sitapur",
    "Laharpur",
    "Biswan",
    "Sevata",
    "Mahmoodabad",
    "Isauli",
    "Sultanpur",
    "Sadar",
    "Lambhua",
    "Kadipur",
    "Bangermau",
    "Safipur",
    "Mohan",
    "Unnao",
    "Bhagwantnagar",
    "Purwa",
    "Rohaniya",
    "Varanasi North",
    "Varanasi South",
    "Varanasi Cantonment",
    "Sevapuri"
  ];
}
